name: Run UI Tests

on:
  workflow_dispatch:  # allows remote triggering
  workflow_call:      # optional: enables repo-to-repo reusable workflows

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
      
      - name: Import secrets to .env file
        run: |
          echo "LANDLORD_USER_EMAIL=${{ secrets.LANDLORD_USER_EMAIL }}" >> .env
          echo "LANDLORD_USER_PASSWORD=${{ secrets.LANDLORD_USER_PASSWORD }}" >> .env

          echo "ADMIN_USER_EMAIL=${{ secrets.ADMIN_USER_EMAIL }}" >> .env
          echo "ADMIN_USER_PASSWORD=${{ secrets.ADMIN_USER_PASSWORD }}" >> .env

          echo "TenantA_USER_EMAIL=${{ secrets.TenantA_USER_EMAIL }}" >> .env
          echo "TenantA_USER_PASSWORD=${{ secrets.TenantA_USER_PASSWORD }}" >> .env

          echo "TenantB_USER_EMAIL=${{ secrets.TenantB_USER_EMAIL }}" >> .env
          echo "TenantB_USER_PASSWORD=${{ secrets.TenantB_USER_PASSWORD }}" >> .env

      - name: Run tests
        run: tests/before_login_tests.py 
